Location details UI
KozakKamil/TourDeOpole pull request #11
Opened 2023-03-23 22:11 UTC by Leohtberend

Added location details UI

2023-03-24 08:52 UTC, KozakKamil requested changes

2023-03-24 08:52 UTC, KozakKamil commented on TourDeOpole/TourDeOpole/Views/PlaceView.xaml
UI nie za bardzo wygląda tak jak na mockupie, dodatkowo jest w złym miejscu

2023-03-24 08:53 UTC, KozakKamil commented on TourDeOpole/TourDeOpole/Views/PlaceView.xaml
Powinien być w PlaceDetailsView, nie w PlaceView
Obrazek powinien być okrągły 
Inny kolor backgroundu

2023-03-30 16:42 UTC, NSzymczak requested changes

2023-03-30 16:42 UTC, NSzymczak commented on TourDeOpole/TourDeOpole/Views/PlaceDetailsView.xaml
> +             Shell.NavBarIsVisible="False"
Tutaj jak dasz True to pojawi ci się pasek i z niego korzystajmy nie z takiego zrobionego samemu bo potem ciężko będzie z nawigacją. Jedyny problem będzie z tym obrazkiem udostępniania, to się da zrobić chyba z jakiejś paczki ale możesz na razie to olać.

2023-03-30 16:42 UTC, NSzymczak commented on TourDeOpole/TourDeOpole/Views/PlaceDetailsView.xaml
> +        <Image Source="Share.png" Grid.Column="4" Grid.Row="0" HorizontalOptions="Center" VerticalOptions="End"/>
To już nie będzie potrzebne jak się włączy ten pasek

2023-03-30 16:42 UTC, NSzymczak commented on TourDeOpole/TourDeOpole/Resources/Colors.xaml
> +    <Color x:Key="Secondary">#2196C3</Color>
Tego chyba nie używasz nigdzie

2023-03-31 06:44 UTC, KozakKamil approved these changes

2023-03-31 06:45 UTC, NSzymczak approved these changes

2023-03-31 06:45 UTC, merged