added Dodawanie Tras UI
KozakKamil/TourDeOpole pull request #29
Opened 2023-04-27 18:26 UTC by robsant

2023-04-27 19:47 UTC, NSzymczak requested changes

2023-04-27 19:47 UTC, NSzymczak commented on TourDeOpole/TourDeOpole/Views/AddTripView.xaml.cs
> +
Warto kliknąć Ctrl K D żeby się kod sformatował. Plus ładniej by to było tak 
```suggestion
         var dynamicPicker = new Picker()
            {
                Margin = new Thickness(5, 5, 0, 0),
            };
            var frame = new Frame()
            {
                Margin = new Thickness(0, 10, 0, 10),
                CornerRadius = 10,
                Padding = 0,
                BorderColor = Color.LightGray,
                Content = dynamicPicker
            };

            AddTripViewLayout.Children.Add(frame);
            Count++;

```

2023-04-27 19:47 UTC, NSzymczak commented on TourDeOpole/TourDeOpole/Views/AddTripView.xaml
> +                         Margin="-120,-90,0,0"
Zrezygnowałabym z tak szalonych marginów bo to na każdym telefonie będzie inaczej wyglądać

2023-04-27 19:47 UTC, NSzymczak commented on TourDeOpole/TourDeOpole/Views/AddTripView.xaml
> +            <ImageButton Grid.Row="2"
To na pewno może być zwykły image bo nie mamy żadnej funkcjonalności po kliknięciu. A może wgl zwykły label?

2023-04-28 10:35 UTC, KozakKamil approved these changes
git

2023-04-28 10:35 UTC, merged